# Generated by Django 5.2.5 on 2025-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(default='pfps/default_userprofile_picture.png', upload_to='pfps'),
        ),
    ]
