# Generated by Django 5.2.5 on 2025-09-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
