# Generated by Django 5.2.5 on 2025-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_company_userprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='professional_status',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Junior Developer', 'Junior'), ('Senior Developer', 'Senior'), ('Manager', 'Manager'), ('Student or Learning', 'Student'), ('Instructor or Teacher', 'Instructor'), ('Intern', 'Intern'), ('Other', 'Other')], default='Developer', max_length=40),
        ),
    ]
