# Generated by Django 5.2.5 on 2025-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_professional_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='professional_status',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Junior Developer', 'Junior Developer'), ('Senior Developer', 'Senior Developer'), ('Manager', 'Manager'), ('Student or Learning', 'Student'), ('Instructor', 'Instructor'), ('Intern', 'Intern'), ('Other', 'Other')], default='Developer', max_length=40),
        ),
    ]
