# Generated by Django 5.2.5 on 2025-10-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_professional_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
