# Generated by Django 5.2.5 on 2025-09-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', null=True, unique=True),
        ),
    ]
